//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageBooks_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int idBook { get; set; }
        public string nameCategory { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.DateTime> datePublication { get; set; }
        public Nullable<int> rate { get; set; }
        public byte[] coverImage { get; set; }
    }
}
