//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageBooks_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public int idBorrow { get; set; }
        public string nameStudent { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> dateBorrowStart { get; set; }
        public Nullable<System.DateTime> dateBorrowEnd { get; set; }
        public Nullable<double> price { get; set; }
    }
}
